default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: contacts_dev

test:
  <<: *default
  database: contacts_test

production:
  <<: *default
  database: contacts_prod
